import {createTheme} from '@mui/material/styles';

export const maxGymTheme = createTheme({
    palette: {
        mode: 'dark',
        background: {default: '#090D12', paper: '#101720'},
        primary: {main: '#53C7B7', contrastText: '#071412'},
        secondary: {main: '#7EA1F8'},
        success: {main: '#58D68D'},
        warning: {main: '#F4C95D'},
        error: {main: '#F27C8D'},
        info: {main: '#7EA1F8'},
        text: {primary: '#F2F6FA', secondary: '#A9B5C3', disabled: '#748295'},
        divider: '#263342',
        action: {hover: 'rgba(83,199,183,.08)', selected: 'rgba(83,199,183,.14)', disabledBackground: 'rgba(116,130,149,.12)'},
    },
    shape: {borderRadius: 16},
    typography: {
        fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        h4: {fontSize: 'clamp(1.65rem, 5vw, 2rem)', lineHeight: 1.12, fontWeight: 800, letterSpacing: '-0.035em'},
        h5: {fontSize: '1.35rem', lineHeight: 1.2, fontWeight: 800, letterSpacing: '-0.02em'},
        h6: {fontSize: '1.08rem', lineHeight: 1.3, fontWeight: 750, letterSpacing: '-0.01em'},
        subtitle1: {fontWeight: 700},
        overline: {fontSize: '.72rem', lineHeight: 1.6, fontWeight: 850, letterSpacing: '.09em'},
        button: {fontWeight: 750, textTransform: 'none', letterSpacing: '-0.01em'},
        caption: {lineHeight: 1.4},
    },
    components: {
        MuiCssBaseline: {styleOverrides: {
            html: {backgroundColor: '#090D12', colorScheme: 'dark'},
            body: {backgroundColor: '#090D12', userSelect: 'auto'},
            '::selection': {backgroundColor: 'rgba(83,199,183,.3)', color: '#F2F6FA'},
            '*': {boxSizing: 'border-box', scrollbarColor: '#334456 #090D12'},
            '*:focus-visible': {outline: '3px solid #53C7B7', outlineOffset: '3px'},
            '@media (prefers-reduced-motion: reduce)': {'*': {animationDuration: '0.01ms !important', transitionDuration: '0.01ms !important', scrollBehavior: 'auto !important'}},
        }},
        MuiAppBar: {styleOverrides: {root: {backgroundImage: 'none', boxShadow: 'none'}}},
        MuiPaper: {styleOverrides: {root: {backgroundImage: 'none', border: '1px solid #263342'}}},
        MuiCard: {styleOverrides: {root: {backgroundColor: '#101720', backgroundImage: 'linear-gradient(145deg, rgba(255,255,255,.012), transparent 55%)', boxShadow: 'none', border: '1px solid #263342', borderRadius: 20}}},
        MuiCardContent: {styleOverrides: {root: {padding: 20, '&:last-child': {paddingBottom: 20}}}},
        MuiCardActionArea: {styleOverrides: {root: {borderRadius: 'inherit', transition: 'background-color 180ms ease', '&:hover': {backgroundColor: 'rgba(83,199,183,.045)'}}}},
        MuiButton: {styleOverrides: {root: {minHeight: 48, borderRadius: 12, paddingInline: 16}, containedPrimary: {boxShadow: 'none', '&:hover': {boxShadow: '0 8px 24px rgba(83,199,183,.18)'}}, outlinedPrimary: {backgroundColor: 'rgba(83,199,183,.025)'}}},
        MuiIconButton: {styleOverrides: {root: {minWidth: 48, minHeight: 48, borderRadius: 14}}},
        MuiOutlinedInput: {styleOverrides: {root: {minHeight: 52, borderRadius: 14, backgroundColor: 'rgba(9,13,18,.48)', transition: 'background-color 180ms ease, border-color 180ms ease', '&:hover': {backgroundColor: 'rgba(9,13,18,.68)'}, '&.Mui-focused': {backgroundColor: '#0C1219'}}, input: {paddingBlock: 14}}},
        MuiInputLabel: {styleOverrides: {root: {fontWeight: 600}}},
        MuiChip: {styleOverrides: {root: {height: 32, borderRadius: 10, fontWeight: 700, backgroundColor: 'rgba(169,181,195,.12)'}, outlined: {backgroundColor: 'transparent'}}},
        MuiAlert: {styleOverrides: {root: {borderRadius: 16, border: '1px solid currentColor', backgroundImage: 'none'}, standardInfo: {backgroundColor: 'rgba(126,161,248,.08)'}, standardSuccess: {backgroundColor: 'rgba(88,214,141,.08)'}, standardWarning: {backgroundColor: 'rgba(244,201,93,.08)'}, standardError: {backgroundColor: 'rgba(242,124,141,.08)'}}},
        MuiDialog: {styleOverrides: {paper: {borderRadius: 24, backgroundColor: '#101720', backgroundImage: 'radial-gradient(circle at 100% 0%, rgba(83,199,183,.08), transparent 35%)', margin: 16, width: 'calc(100% - 32px)'}}},
        MuiDialogTitle: {styleOverrides: {root: {fontWeight: 800, letterSpacing: '-.02em'}}},
        MuiTabs: {styleOverrides: {root: {minHeight: 52}, indicator: {height: 3, borderRadius: 3}}},
        MuiTab: {styleOverrides: {root: {minHeight: 52, fontWeight: 750, textTransform: 'none'}}},
        MuiToggleButton: {styleOverrides: {root: {minHeight: 48, borderRadius: 12, fontWeight: 750, textTransform: 'none'}}},
        MuiListItemButton: {styleOverrides: {root: {minHeight: 64, borderRadius: 16, transition: 'background-color 180ms ease', '&.Mui-selected': {backgroundColor: 'rgba(83,199,183,.14)'}}}},
        MuiAvatar: {styleOverrides: {root: {backgroundColor: 'rgba(83,199,183,.14)', color: '#53C7B7', fontWeight: 800}}},
        MuiFab: {styleOverrides: {root: {width: 56, height: 56, borderRadius: 18, boxShadow: '0 12px 32px rgba(0,0,0,.38)'}}},
        MuiBottomNavigationAction: {styleOverrides: {root: {minWidth: 0}, label: {fontSize: '.68rem', fontWeight: 700, '&.Mui-selected': {fontSize: '.7rem'}}}},
        MuiLinearProgress: {styleOverrides: {root: {height: 6, borderRadius: 6, backgroundColor: 'rgba(83,199,183,.12)'}, bar: {borderRadius: 6}}},
        MuiSnackbarContent: {styleOverrides: {root: {borderRadius: 16, border: '1px solid #263342', backgroundColor: '#17212C'}}},
    },
});
