import {createTheme} from '@mui/material/styles';

export const maxGymTheme = createTheme({
    palette: {
        mode: 'dark',
        background: {default: '#0C0E10', paper: '#15181B'},
        primary: {main: '#C8F36B', contrastText: '#152008'},
        secondary: {main: '#7EA1F8'},
        success: {main: '#58D68D'},
        warning: {main: '#F4C95D'},
        error: {main: '#F27C8D'},
        info: {main: '#7EA1F8'},
        text: {primary: '#F2F6FA', secondary: '#A9B5C3', disabled: '#748295'},
        divider: '#2B3035',
        action: {hover: 'rgba(200,243,107,.08)', selected: 'rgba(200,243,107,.14)', disabledBackground: 'rgba(116,130,149,.12)'},
    },
    shape: {borderRadius: 20},
    typography: {
        fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        body1: {fontSize: '.95rem', lineHeight: 1.6},
        body2: {fontSize: '.85rem', lineHeight: 1.5},
        h4: {fontSize: 'clamp(2rem, 6.8vw, 2.65rem)', lineHeight: 1.12, fontWeight: 800, letterSpacing: '-0.035em'},
        h5: {fontSize: '1.4rem', lineHeight: 1.2, fontWeight: 800, letterSpacing: '-0.02em'},
        h6: {fontSize: '1.08rem', lineHeight: 1.3, fontWeight: 750, letterSpacing: '-0.01em'},
        subtitle1: {fontWeight: 700},
        overline: {fontSize: '.72rem', lineHeight: 1.6, fontWeight: 850, letterSpacing: '.09em'},
        button: {fontWeight: 750, textTransform: 'none', letterSpacing: '-0.01em'},
        caption: {lineHeight: 1.4},
    },
    components: {
        MuiCssBaseline: {styleOverrides: {
            html: {backgroundColor: '#0C0E10', colorScheme: 'dark'},
            body: {backgroundColor: '#0C0E10', userSelect: 'auto', fontVariantNumeric: 'tabular-nums'},
            '::selection': {backgroundColor: 'rgba(200,243,107,.3)', color: '#F2F6FA'},
            '*': {boxSizing: 'border-box', scrollbarColor: '#334456 #0C0E10'},
            '*:focus-visible': {outline: '3px solid #C8F36B', outlineOffset: '3px'},
            '@media (prefers-reduced-motion: reduce)': {'*': {animationDuration: '0.01ms !important', transitionDuration: '0.01ms !important', scrollBehavior: 'auto !important'}},
        }},
        MuiAppBar: {styleOverrides: {root: {backgroundImage: 'none', boxShadow: 'none'}}},
        MuiPaper: {styleOverrides: {root: {backgroundImage: 'none', border: '1px solid #2B3035'}}},
        MuiCard: {styleOverrides: {root: {backgroundColor: '#15181B', backgroundImage: 'none', boxShadow: 'none', border: '1px solid #2B3035', borderRadius: 24}}},
        MuiCardContent: {styleOverrides: {root: {padding: 20, '&:last-child': {paddingBottom: 20}}}},
        MuiCardActionArea: {styleOverrides: {root: {borderRadius: 'inherit', transition: 'background-color 180ms ease', '&:hover': {backgroundColor: 'rgba(200,243,107,.045)'}}}},
        MuiButton: {styleOverrides: {root: {minHeight: 48, borderRadius: 14, paddingInline: 20}, containedPrimary: {boxShadow: 'none', '&:hover': {boxShadow: '0 8px 24px rgba(200,243,107,.18)'}}, outlinedPrimary: {backgroundColor: 'rgba(200,243,107,.025)'}}},
        MuiIconButton: {styleOverrides: {root: {minWidth: 48, minHeight: 48, borderRadius: 14}}},
        MuiOutlinedInput: {styleOverrides: {root: {minHeight: 52, borderRadius: 14, backgroundColor: 'rgba(12,14,16,.48)', transition: 'background-color 180ms ease, border-color 180ms ease', '&:hover': {backgroundColor: 'rgba(12,14,16,.68)'}, '&.Mui-focused': {backgroundColor: '#0C1219'}}, input: {paddingBlock: 14}}},
        MuiInputLabel: {styleOverrides: {root: {fontWeight: 600}}},
        MuiChip: {styleOverrides: {root: {height: 30, borderRadius: 8, fontWeight: 700}, outlined: {backgroundColor: 'transparent'}, clickable: {minHeight: 48}}},
        MuiAlert: {styleOverrides: {root: {borderRadius: 16, border: '1px solid rgba(255,255,255,.1)', backgroundImage: 'none'}, standardInfo: {backgroundColor: 'rgba(126,161,248,.08)'}, standardSuccess: {backgroundColor: 'rgba(88,214,141,.08)'}, standardWarning: {backgroundColor: 'rgba(244,201,93,.08)'}, standardError: {backgroundColor: 'rgba(242,124,141,.08)'}}},
        MuiDialog: {styleOverrides: {paper: {borderRadius: 24, backgroundColor: '#15181B', backgroundImage: 'none', margin: 16, width: 'calc(100% - 32px)', '@media (max-width:599px)': {margin: 0, marginTop: 'auto', width: '100%', maxHeight: '90dvh', borderRadius: '28px 28px 0 0', paddingBottom: 'env(safe-area-inset-bottom)'}, '&.MuiDialog-paperFullScreen': {margin: 0, width: '100%', maxHeight: '100%', borderRadius: 0}}}},
        MuiDialogActions: {styleOverrides: {root: {padding: 20, gap: 8, flexWrap: 'wrap'}}},
        MuiDialogTitle: {styleOverrides: {root: {fontWeight: 800, letterSpacing: '-.02em'}}},
        MuiTabs: {styleOverrides: {root: {minHeight: 52}, indicator: {height: 3, borderRadius: 3}}},
        MuiTab: {styleOverrides: {root: {minHeight: 52, fontWeight: 750, textTransform: 'none'}}},
        MuiToggleButton: {styleOverrides: {root: {minHeight: 48, borderRadius: 12, fontWeight: 750, textTransform: 'none'}}},
        MuiListItemButton: {styleOverrides: {root: {minHeight: 64, borderRadius: 16, transition: 'background-color 180ms ease', '&.Mui-selected': {backgroundColor: 'rgba(200,243,107,.14)'}}}},
        MuiAvatar: {styleOverrides: {root: {backgroundColor: 'rgba(200,243,107,.14)', color: '#C8F36B', fontWeight: 800}}},
        MuiFab: {styleOverrides: {root: {width: 56, height: 56, borderRadius: 18, boxShadow: '0 12px 32px rgba(0,0,0,.38)'}}},
        MuiBottomNavigationAction: {styleOverrides: {root: {minWidth: 0}, label: {fontSize: '.68rem', fontWeight: 700, '&.Mui-selected': {fontSize: '.7rem'}}}},
        MuiLinearProgress: {styleOverrides: {root: {height: 6, borderRadius: 6, backgroundColor: 'rgba(200,243,107,.12)'}, bar: {borderRadius: 6}}},
        MuiSnackbarContent: {styleOverrides: {root: {borderRadius: 16, border: '1px solid #2B3035', backgroundColor: '#20252A'}}},
    },
});
